# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CHAT(object):
    def setupUi(self, CHAT):
        CHAT.setObjectName("CHAT")
        CHAT.resize(565, 525)
        self.centralwidget = QtWidgets.QWidget(CHAT)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(70, 70, 70)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.friend_name = QtWidgets.QLabel(self.frame)
        self.friend_name.setObjectName("friend_name")
        self.verticalLayout_2.addWidget(self.friend_name)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_2)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 288))
        self.scrollArea.setStyleSheet("background-color: rgb(100, 100, 100)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 505, 342))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_chat_history = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_chat_history.setFont(font)
        self.label_chat_history.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_chat_history.setObjectName("label_chat_history")
        self.horizontalLayout_3.addWidget(self.label_chat_history)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.input_message = QtWidgets.QLineEdit(self.frame_3)
        self.input_message.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.input_message.setFont(font)
        self.input_message.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_message.setText("")
        self.input_message.setObjectName("input_message")
        self.horizontalLayout.addWidget(self.input_message)
        self.button_send_message = QtWidgets.QPushButton(self.frame_3)
        self.button_send_message.setEnabled(True)
        self.button_send_message.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.button_send_message.setFont(font)
        self.button_send_message.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.button_send_message.setAutoDefault(False)
        self.button_send_message.setFlat(True)
        self.button_send_message.setObjectName("button_send_message")
        self.horizontalLayout.addWidget(self.button_send_message)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        CHAT.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CHAT)
        self.statusbar.setObjectName("statusbar")
        CHAT.setStatusBar(self.statusbar)

        self.retranslateUi(CHAT)
        QtCore.QMetaObject.connectSlotsByName(CHAT)

    def retranslateUi(self, CHAT):
        _translate = QtCore.QCoreApplication.translate
        CHAT.setWindowTitle(_translate("CHAT", "MainWindow"))
        self.friend_name.setText(_translate("CHAT", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700; color:#ffffff;\">Usuário</span></p></body></html>"))
        self.label_chat_history.setText(_translate("CHAT", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700; color:#ffffff;\">sdasd</span></p></body></html>"))
        self.button_send_message.setText(_translate("CHAT", "✅"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CHAT = QtWidgets.QMainWindow()
    ui = Ui_CHAT()
    ui.setupUi(CHAT)
    CHAT.show()
    sys.exit(app.exec_())
